apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

images:
  - name: inventory-api
    newName: us-central1-docker.pkg.dev/aaic-opsrabbit-demo/argocd-demo/inventory-api
    newTag: bootstrap
