apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

images:
  - name: clientfacing-ui
    newName: us-central1-docker.pkg.dev/aaic-opsrabbit-demo/argocd-demo/clientfacing-ui
    newTag: v1

patches:
  - path: service-patch.yaml
