apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clientfacing-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kiran-AppliedAI/argocd-gke-demo.git
    targetRevision: HEAD
    path: k8s/clientfacing-ui/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
